apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME} 
  
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
      
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'catalog-ui:latest'
      source:
        type: Dockerfile
        dockerfile: |
          FROM nginx:alpine
          COPY . /usr/share/nginx/html
          EXPOSE 80
          CMD ["nginx", "-g", "daemon off;"]

      strategy:
        type: Docker
      triggers:
        - type: ConfigChange
        - type: ImageChange
