apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: catalog-ui-build
  
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
      
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'catalog-ui:latest'
      source:
        type: Dockerfile
        dockerfile: |
          FROM httpd:2.4
          COPY . /usr/local/apache2/htdocs/
          EXPOSE 80

      strategy:
        type: Docker
      triggers:
        - type: ConfigChange
        - type: ImageChange
